In [ ]:
import numpy as np
import pandas as pd

#Prepares the values for calculation
h = 1
m = 1
L = 1

#Creates a range of x values from -L/2 to L/2
Real_Space_Grid = np.linspace(-L/2, L/2, 2000)

#I spent half an hour trying to come up with some clever way to do this, but it just so happens numpy just has a built in function that does it for you
#This function calculates all the delta X values 
DeltaX_All = np.diff(Real_Space_Grid)

#All the delta X values should be the same, but I'll average them just to be safe
DeltaX = np.mean(DeltaX_All)

#Testing
print(DeltaX)

0.0005002501250625312


In [ ]:
#Constructs the Off Diagonal Matrix by preparing a 1999 long array of ones and imposing them on the super and sub diagonal
Ones = np.full(1999, 1)
Sup_Diag_Matrix = np.diagflat(Ones, k=1)
Sub_Diag_Matrix = np.diagflat(Ones, k=-1)

#Combines Off Diagonal Matrix with the Identity matrix times negitive 2 to create the Laplacian Matrix
LP_Matrix = Sup_Diag_Matrix + (np.identity(2000) * -2) + Sub_Diag_Matrix



#This will take the matrix times the one over the distance between points squared as requested
Laplacian = (1/(DeltaX**2)) * LP_Matrix


#Tests to see if LP matrix was constructed correctly
print(Laplacian)

[[-7992002.  3996001.        0. ...        0.        0.        0.]
 [ 3996001. -7992002.  3996001. ...        0.        0.        0.]
 [       0.  3996001. -7992002. ...        0.        0.        0.]
 ...
 [       0.        0.        0. ... -7992002.  3996001.        0.]
 [       0.        0.        0. ...  3996001. -7992002.  3996001.]
 [       0.        0.        0. ...        0.  3996001. -7992002.]]


In [94]:
#This is the construction of the hamiltonian
Hamiltionian = -h**2/(2*m) * Laplacian

#And a test to see if it works
print(Hamiltionian)

[[ 3996001.  -1998000.5       -0.  ...       -0.        -0.        -0. ]
 [-1998000.5  3996001.  -1998000.5 ...       -0.        -0.        -0. ]
 [      -0.  -1998000.5  3996001.  ...       -0.        -0.        -0. ]
 ...
 [      -0.        -0.        -0.  ...  3996001.  -1998000.5       -0. ]
 [      -0.        -0.        -0.  ... -1998000.5  3996001.  -1998000.5]
 [      -0.        -0.        -0.  ...       -0.  -1998000.5  3996001. ]]


In [ ]:
#Calculates the Eigenvalues and eigenvector
Eigvals, Eigvec = np.linalg.eig(Hamiltionian)

#Prints Eigenvectors to prove I got them
#print(Eigvec)

#Sorts Eigenvalues
Sorted_Eig = np.sort(Eigvals)



[[ 0.00469793 -0.00464884  0.00459974 ...  0.00509022 -0.0110303
  -0.0080986 ]
 [-0.00929154  0.00919661 -0.00910158 ...  0.01004763 -0.02067434
  -0.01565675]
 [ 0.01367884 -0.01354444  0.01340974 ...  0.01474285 -0.02772009
  -0.02217007]
 ...
 [-0.01367884 -0.01354444 -0.01340974 ...  0.01474285 -0.02772009
  -0.02217007]
 [ 0.00929154  0.00919661  0.00910158 ...  0.01004763 -0.02067434
  -0.01565675]
 [-0.00469793 -0.00464884 -0.00459974 ...  0.00509022 -0.0110303
  -0.0080986 ]]
